In [6]:
import numpy as np

In [7]:
numpy_array=np.array([1,2,3,4,5])

In [8]:
type(numpy_array)

numpy.ndarray

In [9]:
TwoDArray=np.array([[1,2,3],[4,5,6],[7,8,9]])
TwoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
ThreeDArray=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
ThreeDArray

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [11]:
np.float32
np.array([1,2,3,4,5],dtype=float)

array([1., 2., 3., 4., 5.])

In [12]:
np.array([11,12,13],dtype=bool)

array([ True,  True,  True])

In [13]:
empty_list=[]
for i in range(16):
    empty_list.append(i)
print(empty_list)    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [14]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
np.arange(2,21,31)

array([2])

In [16]:
arange_data=np.arange(1,17)

In [17]:
arange_data.shape=(4,4)                

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.random.random((3,4))

array([[0.44341854, 0.82535372, 0.09832811, 0.76895606],
       [0.04185865, 0.55999113, 0.75757523, 0.36576845],
       [0.37906818, 0.94996042, 0.31888258, 0.47048614]])

In [21]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
import numpy as np
print(np.__version__)

2.1.3


In [25]:
array=np.array([1,2,3,4,5])
array.ndim

1

In [26]:
ARray=np.array([[1,2,3,4,5],[6,7,8,9,8]])
ARray


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 8]])

In [27]:
np.array([[1,2,[3,4],[5,6]]],dtype=np.int32).itemsize

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 4) + inhomogeneous part.

In [4]:
# we cwn apply scalar operations with the array in terms of arithmetic operations

In [5]:
a=5                  
b=6                               
a>b

False

In [6]:
array

NameError: name 'array' is not defined